# Generated by Django 5.2 on 2025-04-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facu',
            name='fecha',
            field=models.DateField(null=True),
        ),
    ]
