# Generated by Django 5.2 on 2025-05-01 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infoextra',
            old_name='est',
            new_name='user',
        ),
    ]
