# Generated by Django 5.2 on 2025-05-01 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0004_remove_infoextra_biografia_estudiante'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoextra',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatares/'),
        ),
        migrations.AddField(
            model_name='infoextra',
            name='biografia',
            field=models.TextField(blank=True, null=True),
        ),
    ]
